version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./wordpress:/var/www/html:delegated
      - /home/centos/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: /home/centos/config/nginx/Dockerfile
    volumes:
      - ./wordpress:/var/www/html:delegated
    ports: 
      - 9000:80
    links:
      - db
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_USER=db
      - MYSQL_PASSWORD=password
    volumes:
      - ./mysql:/var/lib/mysql

